Default: &defaults
  database: word-guesser.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: word-guesser_test.sqlite3
  <<: *defaults

Staging:
  database: word-guesser_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: word-guesser_production.sqlite3
  poolsize: 100
  <<: *defaults
